#!/bin/sh

echo "wget myconfig.conf.tmpl from $CONF_TMPL"
wget -nv -O /etc/confd/templates/myconfig.conf.tmpl $CONF_TMPL

echo "wget myconfig.toml from $CONF_TOML"
wget -nv -O /etc/confd/conf.d/myconfig.toml $CONF_TOML

echo "nginx start"
nginx

echo "confd start"
echo $redis_url
confd -interval 3 -client-key $redis_password -backend redis -node $redis_url
